// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVI7dj2tl3pMGpGruVjnH8g6fRUi7aueg',
    appId: '1:639323415165:android:fccbdbf028f962a7f98714',
    messagingSenderId: '639323415165',
    projectId: 'gomin-jungdok',
    storageBucket: 'gomin-jungdok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVllQFxOYkBHGIZTBoz-uQcL_FlZYEbgI',
    appId: '1:639323415165:ios:63b9aabcc3c0e6c8f98714',
    messagingSenderId: '639323415165',
    projectId: 'gomin-jungdok',
    storageBucket: 'gomin-jungdok.firebasestorage.app',
    iosBundleId: 'com.example.gominJungdokMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVllQFxOYkBHGIZTBoz-uQcL_FlZYEbgI',
    appId: '1:639323415165:ios:63b9aabcc3c0e6c8f98714',
    messagingSenderId: '639323415165',
    projectId: 'gomin-jungdok',
    storageBucket: 'gomin-jungdok.firebasestorage.app',
    iosBundleId: 'com.example.gominJungdokMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEF-5jVBuxluTIodQtKtmBFI5xp6fBcJU',
    appId: '1:639323415165:web:067b0a15e070e467f98714',
    messagingSenderId: '639323415165',
    projectId: 'gomin-jungdok',
    authDomain: 'gomin-jungdok.firebaseapp.com',
    storageBucket: 'gomin-jungdok.firebasestorage.app',
    measurementId: 'G-1KBFWZ4139',
  );
}
